// !this component is the root level of the index route

import Footer from './components/Footer' //fixed at bottom of home page
import './globals.css' //css
import { Inter } from 'next/font/google' //fonts

const inter = Inter({ subsets: ['latin'] }) //font optimization

export const metadata = { //handles head tag duties in a function format
  title: 'Google Clone',
  description: 'Generated by create next app',
  icons: {
    icon: '/google_favicon.svg', //can have different favicons for tab per layout.jsx file
  }
}

export default function RootLayout({ children }) { //this file is equivalent to main.jsx and app.js
  return (
    <html lang="en" className='h-screen relative'>
      <body className={`${inter.className} h-full flex flex-col`}>
        <div className='flex-grow'>
        {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
