import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Google Clone',
  description: 'Generated by create next app',
  icons: {
    icon:'/google_favicon.svg',
}
}

export default function RootLayout({ children }) { //this file is equivalent to main.jsx and app.js
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
