import Footer from './components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Google Clone',
  description: 'Generated by create next app',
  icons: {
    icon: '/google_favicon.svg',
  }
}

export default function RootLayout({ children }) { //this file is equivalent to main.jsx and app.js
  return (
    <html lang="en" className='h-screen relative'>
      <body className={`${inter.className} h-full flex flex-col`}>
        <div className='flex-grow'>
        {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
