import SearchNav from '../components/SearchNav'
import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Google Clone',
    description: 'Generated by create next app',
    icons: {
        icon: '/google_favicon.svg',
    }
}

export default function SearchLayout({ children }) { //this file is equivalent to main.jsx and app.js
    return (
            <main className={`${inter.className} h-full flex flex-col`}>
                <SearchNav />
                <div className='flex-grow'>
                    {children}
                </div>
            </main>
    )
}
