// !this component is the root level of the /search route

import SearchNav from '../components/SearchNav' //nav for /search route
import '../globals.css' //need to import global css file in any layout.jsx file
import { Inter } from 'next/font/google' //configures fonts

const inter = Inter({ subsets: ['latin'] }) //font optimization

export const metadata = { //the head tag in a function format
    title: 'Google Clone',
    description: 'Generated by create next app',
    icons: {
        icon: '/google_favicon.svg',
    }
}

export default function SearchLayout({ children }) { //this file is equivalent to main.jsx and app.js
    return (
            <main className={`${inter.className} h-full flex flex-col`}>
                <SearchNav />
                <div className='flex-grow'>
                    {children}
                </div>
            </main>
    )
}
